spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/kips_db2
    username: postgres
    password: password
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/master.xml
    enabled: true
  mail:
     host: smtp.gmail.com
     port: 587
     username: ""
     password: ""
     properties:
       mail:
         smtp:
           ssl:
             trust: "*"
           auth: true
           starttls:
             enable: true
           connection-timeout: 5000
           timeout: 3000
           write-timeout: 5000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2000KB
      max-request-size: 2000KB

file-url:
  product: http://localhost:8080/api/file/download/product/
  review: http://localhost:8080/api/file/download/review/

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days